# Site settings
title: Andreas Karlsson
email: mail@andreas-karlsson.com
description: > # this means to ignore newlines until "baseurl:"
    Somthing written here
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://andreas-karlsson.com" # the base hostname & protocol for your site
twitter_username: akarl_
github_username:  akarl818

# Build settings
markdown: kramdown
